import yahoodict
#results = yahoodict.lookup(word="放火", yomi="ほうか")
#yahoodict.lookup(word="星占い")
#yahoodict.lookup(word="青二才")
#yahoodict.lookup(word="諦め")
#yahoodict.lookup(word="悪性腫瘍")
#yahoodict.lookup(word="朝晩")
#yahoodict.lookup(word="あぜ道")
#yahoodict.lookup(word="頭が悪い")
#yahoodict.lookup(word="辺り")
#yahoodict.lookup(word="圧力団体")
yahoodict.lookup(word="後始末")
yahoodict.lookup(word="亜熱帯")
yahoodict.lookup(word="あらかじめ")
#print(yahoodoct.pp(results))
